export const dynamic = 'force-dynamic';
// src/app/api/patients/route.ts
// GET — List patients (DOCTOR + OWNER only, clinic-scoped)
// POST — Create patient (DOCTOR + OWNER, generates accessToken automatically)
// This is the EXAMPLE of how every protected route must be written

import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { prisma } from '@/lib/prisma'
import {
  requireRole,
  checkSubscription,
  enforceClinicIsolation,
} from '@/lib/auth/middleware-helpers'

// ── GET: List patients scoped to clinic ──────────────────────────────────────
export async function GET(req: NextRequest) {
  // Step 1: Require DOCTOR or OWNER role
  const auth = await requireRole(req, ['OWNER', 'DOCTOR', 'STAFF'])
  if (auth.error) return auth.error

  const { clinicId } = auth.context!

  // Step 2: Check subscription
  const subError = await checkSubscription(clinicId)
  if (subError) return subError

  // Step 3: Query — ALWAYS filter by clinicId
  const { searchParams } = new URL(req.url)
  const page = parseInt(searchParams.get('page') ?? '1')
  const limit = parseInt(searchParams.get('limit') ?? '20')
  const status = searchParams.get('status') ?? undefined
  const search = searchParams.get('search') ?? undefined

  const where: any = {
    clinicId,  // ← ALWAYS present — no exceptions
    ...(status && { status }),
    ...(search && {
      OR: [
        { name: { contains: search, mode: 'insensitive' } },
        { phone: { contains: search } },
      ],
    }),
  }

  const [patients, total] = await Promise.all([
    prisma.patient.findMany({
      where,
      skip: (page - 1) * limit,
      take: limit,
      orderBy: { createdAt: 'desc' },
      // ← Never return accessToken in list view
      select: {
        id: true, clinicId: true, name: true, phone: true, email: true,
        status: true, riskScore: true, surgeryDate: true, gender: true,
        createdAt: true, updatedAt: true,
        procedure: { select: { name: true, category: true } },
        _count: { select: { tasks: true, billingEvents: true } },
      },
    }),
    prisma.patient.count({ where }),
  ])

  return NextResponse.json({
    success: true,
    data: { patients, total, page, totalPages: Math.ceil(total / limit) },
    timestamp: new Date().toISOString(),
  })
}

// ── POST: Create patient (doctor creates, system generates accessToken) ───────
const createPatientSchema = z.object({
  name: z.string().min(2).max(100),
  phone: z.string().regex(/^\+[1-9]\d{6,14}$/),
  email: z.string().email().optional(),
  dateOfBirth: z.string().optional(),
  gender: z.enum(['MALE', 'FEMALE', 'OTHER']).optional(),
  procedureId: z.string().optional(),
  surgeryDate: z.string().optional(),
  notes: z.string().optional(),
})

export async function POST(req: NextRequest) {
  // Step 1: Only DOCTOR or OWNER can create patients
  const auth = await requireRole(req, ['OWNER', 'DOCTOR'])
  if (auth.error) return auth.error

  const { clinicId } = auth.context!

  // Step 2: Subscription check
  const subError = await checkSubscription(clinicId)
  if (subError) return subError

  try {
    const body = await req.json()
    const parsed = createPatientSchema.safeParse(body)

    if (!parsed.success) {
      return NextResponse.json({ success: false, error: parsed.error.issues[0].message }, { status: 400 })
    }

    const data = parsed.data

    // Check phone uniqueness within clinic
    const existing = await prisma.patient.findFirst({
      where: { phone: data.phone, clinicId }, // ← scoped to clinic
    })
    if (existing) {
      return NextResponse.json({ success: false, error: 'A patient with this phone number already exists in this clinic.' }, { status: 409 })
    }

    // Create patient — accessToken is auto-generated UUID (via Prisma default)
    const patient = await prisma.patient.create({
      data: {
        clinicId,  // ← Always set from JWT, never from request body
        name: data.name,
        phone: data.phone,
        email: data.email,
        dateOfBirth: data.dateOfBirth ? new Date(data.dateOfBirth) : undefined,
        gender: data.gender,
        procedureId: data.procedureId,
        surgeryDate: data.surgeryDate ? new Date(data.surgeryDate) : undefined,
        notes: data.notes,
        status: 'PRE_OP',
        riskScore: 0,
        // accessToken is auto-generated by Prisma @default(uuid())
      },
    })

    return NextResponse.json({
      success: true,
      data: {
        patient: {
          id: patient.id,
          name: patient.name,
          phone: patient.phone,
          status: patient.status,
          accessToken: patient.accessToken, // ← Return to doctor to share with patient
        },
      },
      timestamp: new Date().toISOString(),
    }, { status: 201 })

  } catch (error) {
    console.error('[CREATE PATIENT]', error)
    return NextResponse.json({ success: false, error: 'Failed to create patient.' }, { status: 500 })
  }
}
